### ISSUE TITLE
Apply for 501(c) w/IRS

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/community#19]
Save money by obtaining federal income tax exemption. This is most difficult and costly step of setting up a nonprofit.

IRS Form 1023
https://www.irs.gov/pub/irs-pdf/f1023.pdf

**Comment by Allen616** [comment]
Intro to process.

http://www.dmlp.org/legal-guide/introduction-501c3-application-process

**Comment by Allen616** [comment]
First draft of application has been completed. Shared with Lee.

**Comment by joel6653** [comment]
Happy to help, just not this weekend. See y'all next week.

**Comment by Allen616** [comment]
FYI I have noticed the application is a pdf form does not travel well when sent by email or saved to Google drive. The application which is partially complete is on my laptop.
