### ISSUE TITLE
Business Licenses & Permits

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/community#22]
Don't think we need any of this.

**Comment by BrandonKlotz** [comment]
The State of Michigan does not have a generic business license. Several occupations and industries/services are required to be licensed by the State of Michigan. Depending on the specific type of business or manufacturing operation, some type of certification, license or permit may be required. Access the State License Search site for licensed occupations information (search) online at: www.michigan.gov/statelicensesearch

**Comment by BrandonKlotz** [comment]
I thought it may be worthy to find an organization that is similar to us and search but couldn't think of any off the top of my head. Looked on http://www.michigan.gov/statelicensesearch/0,4671,7-180-24786-81461--,00.html but didn't see anything we needed.

**Comment by Allen616** [comment]
I am going to close this out. We may need a license for certain fundraising activities.
