### ISSUE TITLE
Register with meetup.com

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/community#25]
When we have the funding to do so, I think we should register with meetup.com as a means to attract interested citizens to our hack nights.

- [ ] Depends on #6 (501c3)

**Comment by BrandonKlotz** [comment]
Registered Citizen Labs with Meetup through gmail account. 
To Organize a "Meetup" requires a subscription.

**Comment by BrandonKlotz** [comment]
I am waiting to finish setting this up until we have a bank account.

**Comment by jacebrowning** [comment]
@BrandonKlotz Do you owe Meetup account information right away? I thought they let you get started with a free trial.

**Comment by jacebrowning** [comment]
We'll also want to add the group link to https://hub.citizenlabs.org/

**Comment by BrandonKlotz** [comment]
They must of noticed it sitting in the cart and sent me a 50% option which allowed it to be cost effective. That's why I decided to go the paid route.
