### ISSUE TITLE
Create bank account

### ISSUE THREAD

**Issue by BrandonKlotz** [citizenlabsgr/community#29]

**Comment by joel6653** [comment]
Are we doing this immediately, or waiting until we get our IRS tax status confirmed? I think the bank(s) might be more willing to issue certain types of accounts if we are officially non-profit. But I'll check at my bank(s).

**Comment by BrandonKlotz** [comment]
From the sounds of it you are able to set up a bank account for a business/organization without full tax exemption since Tax Exemption is proactive. So if someone was to donate to us tomorrow they would be able to claim an exempt donation once we are approved.

**Comment by joel6653** [comment]
Yeah, that's not the part of it I was referring to. The bank might be giving free checking accounts to non-profits, while charging for a business account.

**Comment by BrandonKlotz** [comment]
We are currently a non profit organization. We just don't have tax exemption.

**Comment by jacebrowning** [comment]
LMCU offers free business checking: https://www.lmcu.org/commercial/free_checking.aspx

**Comment by joel6653** [comment]
Good, thanks. I'm already a member, too.

**Comment by Allen616** [comment]
We are an incorporated nonprofit. As the Secretary, Max is now in possession of the original forms if originals are needed - they are part of the Corporate Records Book. To confirm, the bank can go to the State of Michigan, LARA database of corporations, and we will be listed there also.

**Comment by joel6653** [comment]
I'm pretty sure that they will also want a Federal Tax ID Number. (But I could be wrong.)
