### ISSUE TITLE
Response to IRS

### ISSUE THREAD

**Issue by Allen616** [citizenlabsgr/community#33]
IRS has requested additional information regarding out 501c3 request.

- Articles of Incorporation
- Narrative Description of Activities
- 3 yr proposed budget
- Financial Transactions With Any Donors?

**Comment by Allen616** [comment]
Link to draft response:

https://docs.google.com/document/d/1j5JJw8gpvfzwp3PZgPYroymP94M4PQsUauAByrbcsvA/edit?usp=sharing

**Comment by BrandonKlotz** [comment]
From what we talked about last Hack night the response looks good to me.

**Comment by Allen616** [comment]
Thx. There have been no other comments. Will submit tomorrow to IRS.
