### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by BrandonKlotz** [citizenlabsgr/community#38]

**Comment by BrandonKlotz** [comment]
Do we want to do anything for a launch such as fundraising, kickstarter, event?

**Comment by Allen616** [comment]
I think we do once we have the 501c3 status, again hopefully soon. We should to [register with the State, this requires completion of 501c3 status.](https://waffle.io/citizenlabsgr/community)

**Comment by Allen616** [comment]
I am going to close this one given that we are past this opportunity. Certainly something like this could be done on an anniversary.
