### ISSUE TITLE
Register with Facebook (For Non-Profits)

### ISSUE THREAD

**Issue by BrandonKlotz** [citizenlabsgr/community#39]

**Comment by BrandonKlotz** [comment]
/Users/brandonklotz/Desktop/Facebook Charity.png

**Comment by BrandonKlotz** [comment]
<img width="677" alt="facebook charity" src="https://cloud.githubusercontent.com/assets/19940878/25569468/26003e8a-2de6-11e7-8078-73d5b4ed0984.png">

Facebook Charity Registration requires the following:

Page Verification: Pending
Community Standards Review: Pending
Create Donations Account: 
• Your organization's official name, address, contact info, tax ID and NTEE category.
• Your CEO or executive director's name, date of birth and contact info.
• Info about the US bank account where you want to receive donations, including a digital copy of an official bank statement or letter, the account holder's name, the account name and ACH routing number. A PayPal account won't work.

**Comment by joel6653** [comment]
I have made note of the fact that we need our bank account to proceed. I am still trying to get Max's signature, but will proceed without it after Tuesday this week.

**Comment by BrandonKlotz** [comment]
Update, we've been approved as a verified page and met community standards review: 

<img width="678" alt="screen shot 2017-05-02 at 2 42 53 pm" src="https://cloud.githubusercontent.com/assets/19940878/25633736/29913bec-2f46-11e7-98ff-61bdd9de7d2c.png">
