### ISSUE TITLE
Apply for non-profit social media manager plan (Hootsuite, Buffer, etc.)

### ISSUE THREAD

**Issue by BrandonKlotz** [citizenlabsgr/community#41]

**Comment by BrandonKlotz** [comment]
Submitted their application process tonight.

"Thank you for your application for our Non-Profit discount!

Your request has been received and is in the process of being reviewed. Once processed, we will reach out to you.

While application volume can vary at any time, we aim to have your application processed within the next 5 - 7 business days.

Regards,

The Hootsuite Team"

**Comment by BrandonKlotz** [comment]
<img width="1281" alt="screen shot 2017-05-02 at 3 11 24 pm" src="https://cloud.githubusercontent.com/assets/19940878/25634721/a6f6452a-2f49-11e7-8ab0-44ad64632dda.png">

**Comment by Allen616** [comment]
Have you created or attached it to an existing account?

**Comment by joel6653** [comment]
@Allen616 I don't understand the question.

**Comment by Allen616** [comment]
@joel6653 Sorry, that question was directed to @BrandonKlotz. The instructions above from Hootsuite said the nonprofit discount could be added to an existing account or used on a new account. I was wondering if @BrandonKlotz had gone down one of those paths.

**Comment by Allen616** [comment]
I sent in documentation to Buffer today. Like Hootsuite, they offer 50% off their pricing. Per, Brandon's suggestion we may use them to begin with. They have a cheaper plan $10/month ($99/month for hootsuite), the downside is that we will have to use a single sign-in instead of team.

**Comment by Allen616** [comment]
Did a bit more digging on Buffer pricing, It looks like we can just add another individual to the Awesome Plan, so with the 50% off it would come to $10/month for two people:

Awesome Plan $10/month: Up to 5 team members can be purchased for an additional $10/month per team member
Small Business Plan $99/month: 5 team members included
Medium Business Plan $199/month: 10 team members included
Large Business Plan $399/month: 25 team members included

**Comment by Allen616** [comment]
We now have a Buffer account for Citizen Labs.
