### ISSUE TITLE
What is our primary email contact?

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/community#51]
info@citizenlabs.org (listed on the website) bounces. We should fix this on the homepage.

**Comment by joel6653** [comment]
In my Google account for Citizen Labs, I do not see the Admin icon in my apps list (like I do for another G-Suite account that I administer), so I'm assuming that either Allen or Jace or both have control over the email accounts.

**Comment by Allen616** [comment]
I am trying to create a Google Group with the email address as info@citizenlabs.org. That way multiple people can see and respond to incoming emails. We could do an alias, but my understanding is that an alias can only go to a single person - not a group.

**Comment by joel6653** [comment]
I faced the same problem with another groups a couple years ago. We ended up making it a behind-the-scenes distribution list (not visible to the sender up front), but it's been kind of clumsy, since it's so hard to tell who has seen and/or responded to the messages.

**Comment by Allen616** [comment]
info@citizenlabs.org &  hello@citizenlabs.org are now in a collaborative inbox that all Board Members are free to join. Invitations to join the group has been sent out.
